# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TvMaze' do
	pod "PromiseKit", "~> 6.8"
	pod 'Alamofire', '~> 5.0.0-rc.2'
	pod 'Kingfisher', '~> 5.0'
  
  target 'TvMazeTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
